### ISSUE TITLE
Update summary table text color

### ISSUE THREAD

**Issue by sfregosi** [PIFSC-Protected-Species-Division/cruise-maps-live#2]
Summary table has black text and a transparent background so it doesn't look good on the website. Try @kmyano suggested colors:

Wanna try purple (#7F7FFF) for the table title, then white for the text. If you have a subheading, you can try the green (#93D500). For completion sake, the teal on the website is #57B8E0.

**Comment by sfregosi** [comment]
Placeholder summary table is now uploaded https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/blob/main/outputs/summaryTable_placeholder_color.png commit [3dba2d5](https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/commit/3dba2d58084571dcdf06606c1d703575f611d718)

I haven't added it to the website yet, although I did try adding it and I think it looks pretty good, but I did not 'publish' my chages. But maybe @kmyano @ybarkley we can all look at it together?

**Comment by ybarkley** [comment]
I really like the colors @sfregosi , it stands out nicely on the website. I don't have any changes.
