### ISSUE TITLE
Change legend title for "Encounters" list

### ISSUE THREAD

**Issue by ybarkley** [PIFSC-Protected-Species-Division/cruise-maps-live#25]
@badgerjj @sfregosi
Creating this for a suggestion by Amanda, to change the legend titles on the maps to differentiate visual sightings and acoustic encounters. 

- [x] Change "Encounters" to "Sightings" for visual map
- [x] Change "Encounters" to "Acoustic Detections" for acoustic map

This actually lines up better with the Summary Table headers. Let me know what you think.

**Comment by ybarkley** [comment]
Hi! Nice job figuring out the map title!
I see the map titles are the same as the legend titles. WHat about Putting something more specific for the map title, "HICEAS 2023: Visual Observer Effort" & "HICEAS 2023: Passive Acoustic Monitoring Effort" ? These terms are also used on the website in the Methods section.
That way, if someone were to just download the image of the map, they would have all the necessary info to know what is what. @amandalbradford , what do you think?

**Comment by amandalbradford** [comment]
Thanks you two, nice work on the update (and issue tracking)! I was also thinking along those lines @ybarkley, although I wondered about something more scicomm-y, like "What cetaceans are we seeing/hearing during HICEAS 2023?" Or if you want to link back to those website sections, "What cetaceans did the visual observers see during HICEAS 2023?" Not sure the best tense, but something like that?

**Comment by ybarkley** [comment]
I like trying to be more scicomm-y-friendly ;)

What about this:
"What cetaceans have we seen during HICEAS 2023?"  w/ Sightings in the legend title
"What cetaceans have we heard during HICEAS 2023?" w/ Acoustic Detections in the legend title.

**Comment by sfregosi** [comment]
Great team brainstorming, ladies! I love Yvonne's suggestion and have updated with that. Should be updated on the web shortly.
