### ISSUE TITLE
SpeceisCodes csv loads with wrong header name

### ISSUE THREAD

**Issue by ybarkley** [PIFSC-Protected-Species-Division/cruise-maps-live#3]
The SpeciesCodestoNames.csv loads, but the first column with header 'SpCode' loads as "ï..SpCode" for some reason in the plotMap.R script, line 29. It's the 'key' object. 
I changed it to:
  key <- read.csv(file.path(dir_wd, 'inputs', "SpeciesCodestoNames.csv"), fileEncoding="UTF-8-BOM")
The 'fileEncoding' argument solved the issue. Ok for me to push that to repo?

@sfregosi @badgerjj

**Comment by ybarkley** [comment]
Also, found the solution [here](https://stackoverflow.com/questions/28005632/columns-names-not-read-properly-by-read-csv-in-r?rq=3)  on StackOverflow. Still don't know why it happens, but this works.

**Comment by sfregosi** [comment]
hmmm I have seen that before and never had a solution and it seemed to happen sometimes and not others. Maybe it is a mac vs windows issue. Nice find on the solution. 

You should have access to push the fix, but let me know if you run into a problem.

**Comment by sfregosi** [comment]
I pulled the changes and all working. Closing
