### ISSUE TITLE
Close out Leg 2/Set up for Leg 3

### ISSUE THREAD

**Issue by sfregosi** [PIFSC-Protected-Species-Division/cruise-maps-live#34]
Waiting on confirmation of final acoustics file, then can close out Leg 2 and prep for Leg 3.

Close out Leg 2
- [x] Final map run
- [x] Save repository as a release for Leg 2
- [x] Add final Leg 2 figs to README

Set up for Leg 3
- [x] Update `run.R` with Leg 3 info
- [x] Try to see if there is a relatively straightforward fix for #33 
- [x] Try manual run through to ensure folders are set up correctly
- [x] Add leg 3 to TimeZones.csv

**Comment by sfregosi** [comment]
🤞🏼 this actually works with first Leg 3 files :)

**Comment by amandalbradford** [comment]
Hi @sfregosi - Leg 3 has begun! Wondering if you have seen the files from the first two days, and if you are getting them okay?

**Comment by sfregosi** [comment]
@amandalbradford thanks for checking in!! I was on leave/raveling Thurs till today so didn't have a chance to run it before you all left. I'm back now so about to process those first two files. Should have a new map here shortly!

**Comment by sfregosi** [comment]
@amandalbradford I don't have a leg 3 acoustic database yet, so the table is not complete and I'm working on manually making the visual map, but the .GPX files are now up on Google Drive here: https://drive.google.com/drive/u/0/folders/1yscmHW2cZ_uP5V79MlpWnP2-1ziLWusp !!
