### ISSUE TITLE
Possible to have acoustic detections without trackline?

### ISSUE THREAD

**Issue by sfregosi** [PIFSC-Protected-Species-Division/cruise-maps-live#35]
Hi @ybarkley @kmyano,

I got the final leg 2 acoustics file and am working on closing out Leg 2/setting up for Leg 3. On the second to last day, there is a beaked whale acoustic detection that is not on a trackline Is that possible if weather is bad? E.g., visuals would be considered off effort but acoustics could still be working?

[dailyMap_acoustics.png](https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/blob/main/outputs/dailyMap_acoustics.png)

Or is something wrong with the code?

Thanks!
sf.

**Comment by ybarkley** [comment]
Nothing is wrong with the code :)
The last couple of days had really rough seas, Bft 7, so the observers were off effort. But Acoustics can still work and they detected those species. So all good!

**Comment by sfregosi** [comment]
Yay! That was my hope and suspicion. Pretty impressive that it took until the last few days to actually have it happen :)
