### ISSUE TITLE
Species sightings plot out of order if multiple days are loaded at once

### ISSUE THREAD

**Issue by sfregosi** [PIFSC-Protected-Species-Division/cruise-maps-live#5]
See 

https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/blob/main/outputs/map_archive/2023_leg01_OES/dailyMap_2023_leg01_OES_2023-07-24.png

vs 

https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/blob/main/outputs/map_archive/2023_leg01_OES/dailyMap_2023_leg01_OES_2023-07-25.png

- first map was created by YB when just das.723 was uploaded to google drive
- second map created by SF when das.723 and das.724 were uploaded
   - They are downloaded not in name order but most recently uploaded first, so SF's run processed das.724 then das.723
   - The code *should* be sorting these to be in date/time order, but something is going wrong when assigning species IDs
   - Also not sure why the Encounters section of the legend moved above the tracklines (But suspect this may be due to YB running on older version of mapping code)

**Comment by sfregosi** [comment]
The issue is in `plotMap.R` with the order of plotting the species symbols:
```
    geom_sf(data=vsMap, aes(color=SpName, shape = SpName), size = 3)+
```
I manually renamed 'unidentified dolphin' to 'dolphin'. The legend stayed in order green circle = melon-headed, orange triangle = dolphin, purple cross = pilot, but then the actual sightings were plotted orange triangle first (furthest west), then green circle, then purple cross on southpoint (where it should be actually :)

Also interestingly, now tracklines and effort legend is on top of encounters (do not know why...) - but that actually seems to go away when I run the whole function vs stepping through line by line?

**Comment by sfregosi** [comment]
added a sorting line to `plotMap.R` and this seems to have fixed it 

```
      #sort vsMap by species name 
      vsMap = vsMap[order(vsMap$SpName),]

```
@badgerjj Does this solution make sense to you/do you see any potential problems with doing it this way?

**Comment by badgerjj** [comment]
Cant imagine that would cause an issue! Thanks for fixing this--I dont really understand the issue at hand, but if there are future problems I'll dig in a little harder.

**Comment by sfregosi** [comment]
Thanks @badgerjj I agree I'm not totally sure *why* this happens but I figure if this solution will fix it we can just ride this until we have a bigger problem :) 

Will merge this to main branch.

**Comment by sfregosi** [comment]
@ybarkley Wanted to flag this for you because you'll want to pull this before tomorrow so all sightings are correct. 

I'm officially not adding anything else to this today!! 

And the GPX stuff #9 won't affect the plotting.
